apiVersion: v1
kind: Service
metadata:
  name: simple-nginx
  namespace: default
spec:
  type: NodePort
  selector:
    app: simple-nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080